# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_config.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13object_config.proto\"(\n\x07Segment\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07indices\x18\x02 \x03(\r\"O\n\x17\x43ontrollerObjectsConfig\x12\x18\n\x10number_of_pixels\x18\x01 \x02(\r\x12\x1a\n\x08segments\x18\x02 \x03(\x0b\x32\x08.Segment')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Segment.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indices', full_name='Segment.indices', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=63,
)


_CONTROLLEROBJECTSCONFIG = _descriptor.Descriptor(
  name='ControllerObjectsConfig',
  full_name='ControllerObjectsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_pixels', full_name='ControllerObjectsConfig.number_of_pixels', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segments', full_name='ControllerObjectsConfig.segments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=144,
)

_CONTROLLEROBJECTSCONFIG.fields_by_name['segments'].message_type = _SEGMENT
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.message_types_by_name['ControllerObjectsConfig'] = _CONTROLLEROBJECTSCONFIG

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENT,
  __module__ = 'object_config_pb2'
  # @@protoc_insertion_point(class_scope:Segment)
  ))
_sym_db.RegisterMessage(Segment)

ControllerObjectsConfig = _reflection.GeneratedProtocolMessageType('ControllerObjectsConfig', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLEROBJECTSCONFIG,
  __module__ = 'object_config_pb2'
  # @@protoc_insertion_point(class_scope:ControllerObjectsConfig)
  ))
_sym_db.RegisterMessage(ControllerObjectsConfig)


# @@protoc_insertion_point(module_scope)
